### ISSUE TITLE
dataset request error

### ISSUE THREAD

**Issue by HRN1024** [ika-rwth-aachen/Point-Cloud-Compression#1]
Hello , author.
Thank you for your excellent open-source work.
When I request the dataset at https://www.unicaragil.de/en/point-cloud-compression.html, it reports 'CURL_SETOPT(): DISABLING SAFE UPLOADS IS NO LONGER SUPPORTED'.  Is it a mistake?

**Comment by TillBeemelmanns** [comment]
Hi,

there is something wrong with the website. Sorry, for the inconvenience.

Here is a direct download link to the models and the dataset: 
https://rwth-aachen.sciebo.de/s/MLJ4UaDJuVkYtna
Does that work for you ?

Best regards,

Till Beemelmanns
