### ISSUE TITLE
Downloading the dataset encountered an issue.

### ISSUE THREAD

**Issue by RuiqiYing** [ika-rwth-aachen/Point-Cloud-Compression#5]
Hello , author.
Thank you for your　Amazing work！
The dataset and model download link you provided (https://rwth-aachen.sciebo.de/s/MLJ4UaDJuVkYtna) is no longer accessible. Could you please provide a new download link?

**Comment by TillBeemelmanns** [comment]
Hi, can you please try again ? I guess the cloud provider was just offline for a short period. I am able to access all files again.

Best,
Till
